import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import styled from 'styled-components'
import { auth , db } from '../firebase'
import { useAuthState } from 'react-firebase-hooks/auth';
import { ColorLensOutlined } from '@material-ui/icons';



export default function Home() {
  const [user] = useAuthState(auth);
  const realname= user.email
  const displayname= realname.replace('@gmail.com','')
  return (
    <div>
      <Head>
        <title>Airthrough Messenger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet" />

      </Head>
      <Indexwindow>
      <Sidebar />
        <Welcomescreen>
          Welcome Back  {displayname}...
        </Welcomescreen>
      </Indexwindow>
      

    </div>
  )
}


const Indexwindow = styled.div`
display:flex;
@media (max-width: 800px) {
    display:inline-block;
    }
`;

const Welcomescreen = styled.div`
float:right;
padding:15%;
padding-left:8%;
align-items:center;
font-size:80px;
font-family: 'Bebas Neue', cursive;
color: #f0e3ca;
z-index:1;
@media (max-width: 800px) {
  color: #a35709;
    }
`;
